"""Sobol sensitivity index computation and post-processing.

Wraps SALib's ``analyze.sobol`` and provides convenience methods to
extract top-K parameters and format results.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from h2iso.uq.distributions import Parameter


@dataclass
class SobolResult:
    """Sobol sensitivity analysis results."""

    parameter_names: list[str]
    qoi_names: list[str]
    S1: np.ndarray  # (K, Q) first-order indices
    ST: np.ndarray  # (K, Q) total-order indices
    S1_conf: np.ndarray  # (K, Q) confidence intervals
    ST_conf: np.ndarray  # (K, Q) confidence intervals
    raw: dict = field(default_factory=dict)  # full SALib dict

    def top_k(
        self,
        k: int = 8,
        metric: str = "ST",
        qoi_index: int = 0,
    ) -> list[str]:
        """Return the names of the top-*k* most sensitive parameters.

        Parameters
        ----------
        k : int
            Number of parameters to return.
        metric : str
            ``"ST"`` (total-order, default) or ``"S1"`` (first-order).
        qoi_index : int
            Which QoI column to rank by.
        """
        matrix = self.ST if metric == "ST" else self.S1
        col = matrix[:, qoi_index]
        order = np.argsort(col)[::-1][:k]
        return [self.parameter_names[i] for i in order]

    def to_dict(self) -> dict:
        """Serialise key results for JSON export."""
        return {
            "parameter_names": list(self.parameter_names),
            "qoi_names": list(self.qoi_names),
            "S1": self.S1.tolist(),
            "ST": self.ST.tolist(),
            "S1_conf": self.S1_conf.tolist(),
            "ST_conf": self.ST_conf.tolist(),
        }


def analyze_sobol(
    parameters: list[Parameter],
    sample_matrix: np.ndarray,
    qoi_matrix: np.ndarray,
    qoi_names: list[str] | None = None,
    n_base: int = 128,
    seed: int | None = None,
) -> SobolResult:
    """Run Sobol sensitivity analysis on a completed sample matrix.

    The sample_matrix must have been generated by
    :func:`h2iso.uq.sampler.sobol_sample` with the same *n_base* and
    *parameters*. The qoi_matrix must have one row per converged sample
    (rows with NaN/Inf are dropped).

    If the number of converged rows is less than the expected
    ``n_base * (2K + 2)``, the analysis is skipped and a warning is issued.
    """
    K = len(parameters)
    # With calc_second_order=False, saltelli produces N * (K + 2) rows
    expected_n = n_base * (K + 2)

    # Drop rows with NaN / Inf in QoI
    valid = np.isfinite(qoi_matrix).all(axis=1)
    n_valid = valid.sum()

    if n_valid < expected_n:
        raise ValueError(
            f"Expected {expected_n} valid samples for Sobol analysis "
            f"(n_base={n_base}, K={K}), but only {n_valid} are finite. "
            f"Sobol analysis requires the full Sobol sample matrix."
        )

    if n_valid > expected_n:
        # Trim to expected (e.g. if user passed extra rows)
        sample_matrix = sample_matrix[:expected_n]
        qoi_matrix = qoi_matrix[:expected_n]
    elif n_valid < qoi_matrix.shape[0]:
        sample_matrix = sample_matrix[valid]
        qoi_matrix = qoi_matrix[valid]

    try:
        from SALib.analyze import sobol as sobol_analyze
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "SALib is required for Sobol analysis. Install with: pip install SALib"
        ) from exc

    Q = qoi_matrix.shape[1]
    if qoi_names is None:
        qoi_names = [f"QoI_{i}" for i in range(Q)]

    problem = {
        "num_vars": K,
        "names": [p.name for p in parameters],
        "bounds": [[0.0, 1.0]] * K,
    }

    S1_all = np.zeros((K, Q))
    ST_all = np.zeros((K, Q))
    S1_conf_all = np.zeros((K, Q))
    ST_conf_all = np.zeros((K, Q))
    raw_all = {}

    for q in range(Q):
        Si = sobol_analyze.analyze(
            problem,
            qoi_matrix[:, q],
            seed=seed,
            calc_second_order=False,
        )
        S1_all[:, q] = Si["S1"]
        ST_all[:, q] = Si["ST"]
        S1_conf_all[:, q] = Si["S1_conf"]
        ST_conf_all[:, q] = Si["ST_conf"]
        raw_all[qoi_names[q]] = dict(Si)

    return SobolResult(
        parameter_names=[p.name for p in parameters],
        qoi_names=qoi_names,
        S1=S1_all,
        ST=ST_all,
        S1_conf=S1_conf_all,
        ST_conf=ST_conf_all,
        raw=raw_all,
    )
