"""Generate Modelica record and function definitions from h2iso parameter data.

Produces:
- Species record files (one .mo per isotopologue)
- VLE function files (pvap, etc.)
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from h2iso._data import data_path


def _load_json(filename: str) -> dict[str, Any]:
    """Load a JSON parameter file from the data directory."""
    with data_path("parameters", filename) as path:
        with open(path) as f:
            return json.load(f)


def _pvap_python(T: float, params: dict[str, float]) -> float:
    """Evaluate vapor pressure correlation in pure Python (reference impl).

    ln(P/Pa) = C1 + C2/T + C3*ln(T) + C4*T^C5
    """
    ln_P = (
        params["C1"]
        + params["C2"] / T
        + params["C3"] * math.log(T)
        + params["C4"] * T ** params["C5"]
    )
    return math.exp(ln_P)


def generate_species_records(output_dir: str | Path | None = None) -> dict[str, str]:
    """Generate Modelica species record files.

    Each record contains molar mass and critical/triple point properties.

    Parameters
    ----------
    output_dir : str or Path, optional
        If provided, write .mo files to this directory.

    Returns
    -------
    dict[str, str]
        Mapping of filename -> file content.
    """
    species_data = _load_json("species.json")
    pvap_data = _load_json("vapor_pressure.json")

    records = {}
    for sp in species_data["species"]:
        formula = sp["formula"]
        name = sp["name"]
        molar_mass = sp["molar_mass"]

        # Get thermodynamic properties from vapor_pressure.json
        vp = pvap_data["species"].get(formula, {})

        content = f'''\
record HydrogenIsotope_{formula}
  "Species record for {name} ({formula}), generated by h2iso"
  extends Modelica.Icons.Record;

  constant String formula = "{formula}";
  constant String name = "{name}";
  constant Modelica.Units.SI.MolarMass M = {molar_mass:.5f}e-3
    "Molar mass [kg/mol]";
'''
        if vp:
            content += f'''\
  constant Modelica.Units.SI.Temperature T_boiling = {vp["T_boiling_101325Pa"]:.3f}
    "Normal boiling point at 101325 Pa [K]";
  constant Modelica.Units.SI.Temperature T_triple = {vp["T_triple"]:.3f}
    "Triple point temperature [K]";
  constant Modelica.Units.SI.Pressure P_triple = {vp["P_triple_Pa"]:.1f}
    "Triple point pressure [Pa]";
  constant Modelica.Units.SI.Temperature T_critical = {vp["T_critical"]:.3f}
    "Critical temperature [K]";
  constant Modelica.Units.SI.Pressure P_critical = {vp["P_critical_Pa"]:.1f}
    "Critical pressure [Pa]";
'''
        content += f'''\
end HydrogenIsotope_{formula};
'''
        filename = f"HydrogenIsotope_{formula}.mo"
        records[filename] = content

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for fname, content in records.items():
            (out / fname).write_text(content)

    return records


def generate_vle_functions(output_dir: str | Path | None = None) -> dict[str, str]:
    """Generate Modelica vapor pressure function files.

    Each function implements: ln(P/Pa) = C1 + C2/T + C3*ln(T) + C4*T^C5

    Parameters
    ----------
    output_dir : str or Path, optional
        If provided, write .mo files to this directory.

    Returns
    -------
    dict[str, str]
        Mapping of filename -> file content.
    """
    pvap_data = _load_json("vapor_pressure.json")

    functions = {}
    for formula, params in pvap_data["species"].items():
        content = f'''\
function pvap_{formula}
  "Saturation pressure of {formula} [Pa]. Correlation: ln(P/Pa) = C1 + C2/T + C3*ln(T) + C4*T^C5"
  input Modelica.Units.SI.Temperature T "Temperature [K]";
  output Modelica.Units.SI.Pressure P "Saturation pressure [Pa]";
protected
  constant Real C1 = {params["C1"]:.6f};
  constant Real C2 = {params["C2"]:.4f};
  constant Real C3 = {params["C3"]:.6f};
  constant Real C4 = {params["C4"]:.8f};
  constant Real C5 = {params["C5"]:.1f};
algorithm
  P := exp(C1 + C2/T + C3*Modelica.Math.log(T) + C4*T^C5);
  annotation(Documentation(info="<html>
    <p>Valid range: {params["T_min"]:.2f} K &le; T &le; {params["T_max"]:.2f} K</p>
    <p>Source: {params["source"]}</p>
    <p>Generated by h2iso codegen</p>
    </html>"));
end pvap_{formula};
'''
        filename = f"pvap_{formula}.mo"
        functions[filename] = content

    if output_dir is not None:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for fname, content in functions.items():
            (out / fname).write_text(content)

    return functions


def pvap_reference(T: float, species: str) -> float:
    """Compute reference vapor pressure value for validation.

    Uses pure Python math (no numpy) to provide an independent check
    against the Modelica-generated functions.

    Parameters
    ----------
    T : float
        Temperature in Kelvin.
    species : str
        Species formula (H2, HD, HT, D2, DT, T2).

    Returns
    -------
    float
        Vapor pressure in Pa.
    """
    pvap_data = _load_json("vapor_pressure.json")
    params = pvap_data["species"][species]
    return _pvap_python(T, params)
