"""Modelica initialization script generator.

Generates .mos scripts that set initial parameter values in
OpenModelica models from h2iso column results.
"""

from __future__ import annotations

from h2iso.mesh.column import ColumnResult
from h2iso.species import SPECIES_ORDER


def generate_init_script(result: ColumnResult, model_name: str) -> str:
    """Generate a Modelica .mos initialization script.

    Parameters
    ----------
    result : ColumnResult
        Solved column result.
    model_name : str
        Fully qualified Modelica model name (e.g., "Tricys.Distillation.CD2").

    Returns
    -------
    str
        Content of the .mos script.
    """
    N = len(result.T_profile)
    lines = []
    lines.append(f"// Auto-generated by h2iso for model: {model_name}")
    lines.append(f"// N_stages = {N}")
    lines.append("")

    # Temperature profile
    T_str = ", ".join(f"{result.T_profile[j]:.6f}" for j in range(N))
    lines.append(f'setInitXml("{model_name}.T_init", "{{{T_str}}}");')
    lines.append("")

    # Liquid composition
    for i, sp in enumerate(SPECIES_ORDER):
        x_str = ", ".join(f"{result.x_profile[j, i]:.8g}" for j in range(N))
        lines.append(f'setInitXml("{model_name}.x_{sp}_init", "{{{x_str}}}");')
    lines.append("")

    # Vapor composition
    for i, sp in enumerate(SPECIES_ORDER):
        y_str = ", ".join(f"{result.y_profile[j, i]:.8g}" for j in range(N))
        lines.append(f'setInitXml("{model_name}.y_{sp}_init", "{{{y_str}}}");')
    lines.append("")

    # Flow profiles
    L_str = ", ".join(f"{result.L_profile[j]:.6f}" for j in range(N))
    V_str = ", ".join(f"{result.V_profile[j]:.6f}" for j in range(N))
    lines.append(f'setInitXml("{model_name}.L_init", "{{{L_str}}}");')
    lines.append(f'setInitXml("{model_name}.V_init", "{{{V_str}}}");')
    lines.append("")

    # Heat duties
    lines.append(f'setInitXml("{model_name}.Q_cond", "{result.condenser_duty:.4f}");')
    lines.append(f'setInitXml("{model_name}.Q_reb", "{result.reboiler_duty:.4f}");')

    return "\n".join(lines) + "\n"
