"""Three-way parity report: Aspen Plus vs DWSIM vs h2iso.

Generates a Markdown report comparing H/D/T mass flows (g/h) across
the three software packages for all 5 test cases.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from h2iso.parity.cases import load_test_cases


def load_aspen_results() -> list[dict]:
    """Load Aspen baseline results from the fixture JSON."""
    return load_test_cases()


def load_dwsim_results(path: str | Path) -> list[dict]:
    """Load DWSIM results from a JSON file (generated by run_dwsim_baseline.py)."""
    with open(path) as f:
        return json.load(f)


def load_h2iso_results(path: str | Path) -> list[dict]:
    """Load h2iso results from a JSON file."""
    with open(path) as f:
        return json.load(f)


def _match_case(results: list[dict], case_id: str) -> dict | None:
    for r in results:
        if r.get("case_id") == case_id:
            return r
    return None


_STREAMS = ("WDS", "SDSD2", "SDST2")
_ELEMENTS = ("H", "D", "T")


def _safe_div(a: float, b: float) -> float:
    if abs(b) < 1e-15:
        return float("nan")
    return a / b


def _compute_pair_errors(ref_results, test_results):
    """Return list of relative errors for a pair of result sets."""
    errors = []
    for ref_case in ref_results:
        case_id = ref_case.get("case_id", "")
        test_case = _match_case(test_results, case_id)
        if not test_case:
            continue
        for stream in _STREAMS:
            ref_products = ref_case.get(
                "products_atom_flow_g_h", ref_case.get("products", {})
            )
            test_products = test_case.get("products", {})
            ref_p = ref_products.get(stream, {})
            test_p = test_products.get(stream, {})
            for elem in _ELEMENTS:
                rv = ref_p.get(elem, 0.0)
                tv = test_p.get(elem, 0.0)
                if abs(rv) > 1e-6:
                    err = abs(tv - rv) / abs(rv)
                    if np.isfinite(err):
                        errors.append(err)
    return errors


def generate_report(
    aspen: list[dict],
    dwsim: list[dict] | None = None,
    h2iso: list[dict] | None = None,
    title: str = "ISS-I Three-Way Parity Report",
) -> str:
    """Generate a Markdown three-way comparison report."""
    lines: list[str] = []
    lines.append(f"# {title}\n")

    # --- Test Setup ---
    lines.append("## Test Setup\n")
    lines.append("| Software | EOS | Solver | Notes |")
    lines.append("|----------|-----|--------|-------|")
    lines.append(
        "| Aspen Plus V14 | Peng-Robinson | Inside-Out | "
        "Zhang Shikun 2026-05, T2-Threetowers4.bkp |"
    )
    if dwsim:
        lines.append(
            "| DWSIM 9.0.5 | SRK | Simultaneous Correction | "
            "register_compounds.py, kij from Aspen |"
        )
    if h2iso:
        lines.append(
            "| h2iso 0.1.0 | Souers + quantum corr. | "
            "Sequential Modular + Wegstein | Reduced stages |"
        )
    lines.append("")

    # --- Per-Case Tables ---
    for aspen_case in aspen:
        case_id = aspen_case["case_id"]
        feed = aspen_case["feed_atom_flow_g_h"]
        lines.append(f"### {case_id}: {aspen_case['description']}\n")
        lines.append(
            f"Feed: H={feed['H']:.1f}, D={feed['D']:.1f}, T={feed['T']:.1f} g/h\n"
        )

        # Build header
        header_cols = ["Stream", "Element", "Aspen"]
        if dwsim:
            header_cols.append("DWSIM")
        if h2iso:
            header_cols.append("h2iso")
        if dwsim and h2iso:
            header_cols.extend(["A/D %", "A/H %", "D/H %"])
        elif dwsim:
            header_cols.append("A/D %")
        elif h2iso:
            header_cols.append("A/H %")

        lines.append("| " + " | ".join(header_cols) + " |")
        sep = "|" + "|".join(["---"] * len(header_cols)) + "|"
        lines.append(sep)

        dwsim_case = _match_case(dwsim, case_id) if dwsim else None
        h2iso_case = _match_case(h2iso, case_id) if h2iso else None

        for stream in _STREAMS:
            a = aspen_case["products_atom_flow_g_h"].get(stream, {})
            d = dwsim_case["products"].get(stream, {}) if dwsim_case else {}
            h = h2iso_case["products"].get(stream, {}) if h2iso_case else {}

            for elem in _ELEMENTS:
                av = a.get(elem, 0.0)
                dv = d.get(elem, 0.0) if d else None
                hv = h.get(elem, 0.0) if h else None

                cols = [stream, elem, f"{av:.4g}"]
                if dwsim:
                    cols.append(f"{dv:.4g}" if dv is not None else "-")
                if h2iso:
                    cols.append(f"{hv:.4g}" if hv is not None else "-")
                if dwsim and dv is not None and abs(av) > 1e-10:
                    cols.append(f"{abs(av - dv) / abs(av) * 100:.1f}")
                if h2iso and hv is not None and abs(av) > 1e-10:
                    cols.append(f"{abs(av - hv) / abs(av) * 100:.1f}")
                if (
                    dwsim
                    and h2iso
                    and dv is not None
                    and hv is not None
                    and abs(dv) > 1e-10
                ):
                    cols.append(f"{abs(dv - hv) / abs(dv) * 100:.1f}")

                lines.append("| " + " | ".join(cols) + " |")
        lines.append("")

    # --- Summary Table ---
    lines.append("## Summary\n")
    lines.append("| Pair | Mean Rel Error | Max Rel Error |")
    lines.append("|------|---------------|---------------|")

    pairs = []
    if dwsim:
        pairs.append(("Aspen vs DWSIM", aspen, dwsim))
    if h2iso:
        pairs.append(("Aspen vs h2iso", aspen, h2iso))
    if dwsim and h2iso:
        pairs.append(("DWSIM vs h2iso", dwsim, h2iso))

    pair_errors = {}  # label -> list of errors
    for label, ref, test in pairs:
        errors = _compute_pair_errors(ref, test)
        pair_errors[label] = errors
        if errors:
            mean_err = np.mean(errors) * 100
            max_err = np.max(errors) * 100
            lines.append(f"| {label} | {mean_err:.1f}% | {max_err:.1f}% |")
        else:
            lines.append(f"| {label} | N/A | N/A |")
    lines.append("")

    # --- Go/No-Go ---
    lines.append("## Go/No-Go\n")
    lines.append("| Pair | Threshold | Mean Err | Pass? |")
    lines.append("|------|-----------|----------|-------|")
    for label, ref, test in pairs:
        errors = pair_errors.get(label, [])
        if errors:
            m = np.mean(errors) * 100
            thresh = 15.0 if "DWSIM vs h2iso" in label else 10.0
            status = "✅" if m < thresh else "❌"
            lines.append(f"| {label} | {thresh:.0f}% | {m:.1f}% | {status} |")
    lines.append("")

    return "\n".join(lines)


def save_report(
    aspen: list[dict],
    dwsim: list[dict] | None = None,
    h2iso: list[dict] | None = None,
    output_path: str | Path = "parity_report.md",
) -> Path:
    """Generate and save the parity report."""
    output_path = Path(output_path)
    report = generate_report(aspen, dwsim, h2iso)
    output_path.write_text(report)
    return output_path
